### ISSUE TITLE
请改善对中时电子报的支持

### ISSUE THREAD

**Issue by ivysrono** [eight04/No-Embed-YouTube#2]
https://www.chinatimes.com/realtimenews/20190503002555-260407?chdtv

头部的YouTube的确不再是嵌入式，但留下了个大大的黑框。

**Comment by eight04** [comment]
有些網站為了 Youtube 設定了特殊的樣式，就會有這種現象。這種情況下，只能去覆寫網站的樣式。以你的連結為例，可以使用以下的 usercss︰
```css
/* ==UserStyle==
@name           Chinatimes remove video container
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    A new userstyle
@author         Me
==/UserStyle== */

@-moz-document domain("www.chinatimes.com") {
  .video-container::before {
    /* 移除額外的佔位元素 */
    content: none!important;
  }
  .video-container {
    /* 移除額外的背景色 */
    background: none;
  }
}
```
